mappings:
  - sourceBranch: amd-npi
    dependents: #upstream repo details
      - organization: AMD-Radeon-Driver
        repo: compute
        path: hip-tests
        branch: amd/npi/compute
      - organization: AMD-Radeon-Driver
        repo: compute
        path: hip-tests
        branch: amd/npi/gfx11
  - sourceBranch: amd-staging-closed
    dependents: #upstream repo details
      - organization: AMD-Radeon-Driver
        repo: compute
        path: hip-tests
        branch: amd/stg/runtime-closed
  - sourceBranch: amd-staging
    dependents: #upstream repo details
      - organization: AMD-Radeon-Driver
        repo: compute
        path: hip-tests
        branch: amd/stg/runtime
commitJiraTicket: 'SWDEV-4 -'
emailSender: no-reply-github@amd.com
emailRecipients: dl.GitHubSiteAdmin@amd.com
